@@include('../../node_modules/jquery/dist/jquery.min.js')
@@include('../../node_modules/jquery.maskedinput/src/jquery.maskedinput.js')
// @@include('../../node_modules/@fancyapps/fancybox/dist/jquery.fancybox.min.js')
@@include('../../node_modules/swiper/swiper-bundle.js')
@@include('../../node_modules/jquery-ui-slider/jquery-ui.js')
@@include('./jquery.ui.touch-punch.min.js')